---

- name: Find if Redis is already installed
  shell: docker service ls | grep redis
  register: redis_installed
  ignore_errors: yes

- name: Create a directory if it does not exist
  when: redis_installed.stdout == ""
  file:
    path: /mnt/redis
    mode: u+rw,g+wx,o+rwx
    state: directory

- name: Install jsondiff package
  when: redis_installed.stdout == ""
  pip:
    name: jsondiff
    state: present

- name: Copy redis stack file
  when: redis_installed.stdout == ""
  template:
    src: "stack.yml"
    dest: /tmp/redis_stack.yml

- name: Deploy stack from a compose file
  when: redis_installed.stdout == ""
  shell: docker stack deploy -c /tmp/redis_stack.yml redis

- name: Remove stack file
  file:
    path: /tmp/redis_stack.yml
    state: absent

