version: "3.2"

services:
  postgres:
    image: kartoza/postgis:15
    ports:
      - 5432:5432
    volumes:
      - /mnt/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASS_FILE=/run/secrets/postgres_password
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
