version: "3.2"

services:
  postgres:
    image: kartoza/postgis:15
    ports:
      - 5432:5432
    volumes:
      - /mnt/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres_password
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology
