---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Core packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - wget
      - curl
      - gnupg2
      - openssl
      - git
      - build-essential
      - zlib1g-dev
      - libreadline-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - ca-certificates
      - jq
- name: Install keys
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.shell: |
    sudo mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
- name: Add Docker repository
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.shell: |
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Docker packages
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
